#!/usr/bin/env Rscript

library(argparse)
library(data.table)

# for performing residualizing
devtools::load_all('utils/modules/R/gwastools')

main <- function(args){
 
    print(args)  
    stopifnot(file.exists(args$input_path))
    stopifnot(dir.exists(dirname(args$out_path)))
    stopifnot(!is.null(args$covariates))

    # read in data 
    dt <- fread(args$input_path)
    
    # include sprios phenotypes generated by Samvida 
    if (args$include_spiros) {
        
        ## start Samvida's code
      
        eid_pheno_matrix <- read.table("/well/lindgren-ukbb/projects/ukbb-11867/samvida/general_resources/eid_phenotype_matrix.txt",
                             sep = "\t", header = T, stringsAsFactors = F)
        colnames(eid_pheno_matrix) <- gsub("^X", "", colnames(eid_pheno_matrix))
        # Disease dictionary
        dictionary <- read.table("/well/lindgren-ukbb/projects/ukbb-11867/samvida/general_resources/UKB_codelists/chronological-map-phenotypes/annot_dictionary.txt",
                                 sep = "\t", header = T, stringsAsFactors = F, 
                                 quote = "", comment.char = "$")
        PHENOTYPES <- dictionary$phenotype[match(colnames(eid_pheno_matrix)[-1],
                                               dictionary$unique_code)]
        colnames(eid_pheno_matrix)[-1] <- PHENOTYPES

        ## end samvida's code

        # create column names that are sensible and without strnage characters
        cols <- colnames(eid_pheno_matrix)
        cols <- gsub("\\'", "", cols)
        cols <- gsub("\\(.+\\)","", cols) 
        cols <- gsub('\\"', "", cols)
        cols <- gsub("\\-","_", cols)
        cols <- gsub("\\&", "_and_", cols)
        cols <- gsub("\\,","_",cols)
        cols <- gsub("(^\\ *)|(\\ *$)","", cols)
        cols <- gsub("\\ +", " ", cols)
        cols <- gsub("\\ ", "_", cols)
        cols <- gsub("\\_+", "_", cols)
        cols <- tolower(cols)
        colnames(eid_pheno_matrix) <- cols

        # convert to boolean
        spiros_pheno <- eid_pheno_matrix
        spiros_pheno[,-1] <- spiros_pheno[,-1] > 0

        # combine with input data
        mrg <- merge(dt, spiros_pheno, by = "eid", all.x = TRUE)

        # determine overlap between old phenotypes and new phenotypes
        pheno_cols <- names(which(sapply(mrg, is.logical)))

        # discard phenotypes with less than 50 cases in quality controlled samples (200k)
        qc_samples <- fread(args$qc_samples)$V1
        mrg_subset_by_qced_samples <- mrg[mrg$eid %in% qc_samples,]
        lst <- lapply(pheno_cols, function(ph) sum(mrg_subset_by_qced_samples[[ph]], na.rm = TRUE))
        names(lst) <- pheno_cols
        dlst <- stack(lst)
        colnames(dlst) <- c("cases", "phenotype")
        bool_phenos_discard <- dlst$cases < 50
        dlst <- dlst[!bool_phenos_discard, ]
        write(paste("Discarded", sum(bool_phenos_discard), "phenotypes with less than 50 cases."), stdout())
        phenos_keep <- dlst$phenotype

        # subset columns
        cols_keep <- (!(colnames(mrg) %in% pheno_cols)) | (colnames(mrg) %in% phenos_keep)
        mrg <- mrg[,..cols_keep]

        # now work with this as the main table
        dt <- mrg

    }
    
    # append new covariates
    dt$age2 <- dt$age ^ 2
    dt$age3 <- dt$age ^ 3
    dt$sex_age <- dt$age * ifelse(dt$sex == 1, 1, -1)

    # only keep samples in which we have no missing covariates 
    covars <- unlist(strsplit(args$covariates, split = ","))
    missing <- rowSums(do.call(cbind, lapply(covars, function(col) is.na(dt[[col]]) ))) > 0
    n_missing <- sum(missing)
    if ((n_missing > 0) & (args$row_na_action == "remove")) {
        write(paste("Note: dropping", n_missing, "sample(s) with missing covariates."),stderr())
        dt <- dt[!missing, ]
    }

    # transform phenotypes (either RINT or INT)
    if (!is.null(args$transform_method) & !is.null(args$transform)){
       
        # only transform selected phenotypes 
        phenotypes <- unlist(strsplit(args$transform, split = ","))
        phenotypes <- phenotypes[phenotypes %in% colnames(dt)]
        stopifnot(length(phenotypes) > 0)

        # do transformation and aggregate
        f <- ifelse(args$transform_method == "int", gwastools::get_int, gwastools::get_rint)
        transformed_phenos <- lapply(phenotypes, function(ph){ return(f(dt[[ph]])) })
        transformed_phenos <- do.call(cbind, transformed_phenos)
        colnames(transformed_phenos) <- paste0(phenotypes, "_",args$transform_method)
        dt <- cbind(dt, transformed_phenos)
    }



    # Finally write file
    write(paste0("Done! Writing to",args$out_path), stdout())
    fwrite(dt, args$out_path, sep = "\t")
}

# add arguments
parser <- ArgumentParser()
parser$add_argument("--out_path", default=NULL, help = "Where should the file be written")
parser$add_argument("--input_path", default=NULL, help = "Curated phenotypes input path")
parser$add_argument("--transform_method", default=NULL, help = "Transformation of residuals, either INT or RINT")
parser$add_argument("--transform", default=NULL, help = "What phenotypes should be transformed?")
parser$add_argument("--row_na_action", default="keep", help = "set to 'remove' to delete rows with missing covariates")
parser$add_argument("--covariates", default=NULL, help = "comma seperated string of covariates")
parser$add_argument("--qc_samples", default=NULL, help = "link to duncan's quality control samples (only used to subset by phenotype case count!)")
parser$add_argument("--include_spiros", default=FALSE, action='store_true', help = "Include spiros phenotypes.")
args <- parser$parse_args()

main(args)

